// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jipark0716/discordTypecast/ent/predicate"
	"github.com/jipark0716/discordTypecast/ent/typecastmessage"
)

// TypecastMessageQuery is the builder for querying TypecastMessage entities.
type TypecastMessageQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TypecastMessage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TypecastMessageQuery builder.
func (tmq *TypecastMessageQuery) Where(ps ...predicate.TypecastMessage) *TypecastMessageQuery {
	tmq.predicates = append(tmq.predicates, ps...)
	return tmq
}

// Limit adds a limit step to the query.
func (tmq *TypecastMessageQuery) Limit(limit int) *TypecastMessageQuery {
	tmq.limit = &limit
	return tmq
}

// Offset adds an offset step to the query.
func (tmq *TypecastMessageQuery) Offset(offset int) *TypecastMessageQuery {
	tmq.offset = &offset
	return tmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tmq *TypecastMessageQuery) Unique(unique bool) *TypecastMessageQuery {
	tmq.unique = &unique
	return tmq
}

// Order adds an order step to the query.
func (tmq *TypecastMessageQuery) Order(o ...OrderFunc) *TypecastMessageQuery {
	tmq.order = append(tmq.order, o...)
	return tmq
}

// First returns the first TypecastMessage entity from the query.
// Returns a *NotFoundError when no TypecastMessage was found.
func (tmq *TypecastMessageQuery) First(ctx context.Context) (*TypecastMessage, error) {
	nodes, err := tmq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{typecastmessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tmq *TypecastMessageQuery) FirstX(ctx context.Context) *TypecastMessage {
	node, err := tmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TypecastMessage ID from the query.
// Returns a *NotFoundError when no TypecastMessage ID was found.
func (tmq *TypecastMessageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tmq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{typecastmessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tmq *TypecastMessageQuery) FirstIDX(ctx context.Context) int {
	id, err := tmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TypecastMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TypecastMessage entity is found.
// Returns a *NotFoundError when no TypecastMessage entities are found.
func (tmq *TypecastMessageQuery) Only(ctx context.Context) (*TypecastMessage, error) {
	nodes, err := tmq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{typecastmessage.Label}
	default:
		return nil, &NotSingularError{typecastmessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tmq *TypecastMessageQuery) OnlyX(ctx context.Context) *TypecastMessage {
	node, err := tmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TypecastMessage ID in the query.
// Returns a *NotSingularError when more than one TypecastMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (tmq *TypecastMessageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tmq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{typecastmessage.Label}
	default:
		err = &NotSingularError{typecastmessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tmq *TypecastMessageQuery) OnlyIDX(ctx context.Context) int {
	id, err := tmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TypecastMessages.
func (tmq *TypecastMessageQuery) All(ctx context.Context) ([]*TypecastMessage, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tmq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tmq *TypecastMessageQuery) AllX(ctx context.Context) []*TypecastMessage {
	nodes, err := tmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TypecastMessage IDs.
func (tmq *TypecastMessageQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tmq.Select(typecastmessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tmq *TypecastMessageQuery) IDsX(ctx context.Context) []int {
	ids, err := tmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tmq *TypecastMessageQuery) Count(ctx context.Context) (int, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tmq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tmq *TypecastMessageQuery) CountX(ctx context.Context) int {
	count, err := tmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tmq *TypecastMessageQuery) Exist(ctx context.Context) (bool, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tmq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tmq *TypecastMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := tmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TypecastMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tmq *TypecastMessageQuery) Clone() *TypecastMessageQuery {
	if tmq == nil {
		return nil
	}
	return &TypecastMessageQuery{
		config:     tmq.config,
		limit:      tmq.limit,
		offset:     tmq.offset,
		order:      append([]OrderFunc{}, tmq.order...),
		predicates: append([]predicate.TypecastMessage{}, tmq.predicates...),
		// clone intermediate query.
		sql:    tmq.sql.Clone(),
		path:   tmq.path,
		unique: tmq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TypecastMessage.Query().
//		GroupBy(typecastmessage.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tmq *TypecastMessageQuery) GroupBy(field string, fields ...string) *TypecastMessageGroupBy {
	grbuild := &TypecastMessageGroupBy{config: tmq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tmq.sqlQuery(ctx), nil
	}
	grbuild.label = typecastmessage.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.TypecastMessage.Query().
//		Select(typecastmessage.FieldUserID).
//		Scan(ctx, &v)
func (tmq *TypecastMessageQuery) Select(fields ...string) *TypecastMessageSelect {
	tmq.fields = append(tmq.fields, fields...)
	selbuild := &TypecastMessageSelect{TypecastMessageQuery: tmq}
	selbuild.label = typecastmessage.Label
	selbuild.flds, selbuild.scan = &tmq.fields, selbuild.Scan
	return selbuild
}

func (tmq *TypecastMessageQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tmq.fields {
		if !typecastmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tmq.path != nil {
		prev, err := tmq.path(ctx)
		if err != nil {
			return err
		}
		tmq.sql = prev
	}
	return nil
}

func (tmq *TypecastMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TypecastMessage, error) {
	var (
		nodes = []*TypecastMessage{}
		_spec = tmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TypecastMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TypecastMessage{config: tmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tmq *TypecastMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tmq.querySpec()
	_spec.Node.Columns = tmq.fields
	if len(tmq.fields) > 0 {
		_spec.Unique = tmq.unique != nil && *tmq.unique
	}
	return sqlgraph.CountNodes(ctx, tmq.driver, _spec)
}

func (tmq *TypecastMessageQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := tmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (tmq *TypecastMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   typecastmessage.Table,
			Columns: typecastmessage.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: typecastmessage.FieldID,
			},
		},
		From:   tmq.sql,
		Unique: true,
	}
	if unique := tmq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tmq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, typecastmessage.FieldID)
		for i := range fields {
			if fields[i] != typecastmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tmq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tmq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tmq *TypecastMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tmq.driver.Dialect())
	t1 := builder.Table(typecastmessage.Table)
	columns := tmq.fields
	if len(columns) == 0 {
		columns = typecastmessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tmq.sql != nil {
		selector = tmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tmq.unique != nil && *tmq.unique {
		selector.Distinct()
	}
	for _, p := range tmq.predicates {
		p(selector)
	}
	for _, p := range tmq.order {
		p(selector)
	}
	if offset := tmq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tmq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TypecastMessageGroupBy is the group-by builder for TypecastMessage entities.
type TypecastMessageGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tmgb *TypecastMessageGroupBy) Aggregate(fns ...AggregateFunc) *TypecastMessageGroupBy {
	tmgb.fns = append(tmgb.fns, fns...)
	return tmgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tmgb *TypecastMessageGroupBy) Scan(ctx context.Context, v any) error {
	query, err := tmgb.path(ctx)
	if err != nil {
		return err
	}
	tmgb.sql = query
	return tmgb.sqlScan(ctx, v)
}

func (tmgb *TypecastMessageGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range tmgb.fields {
		if !typecastmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tmgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tmgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tmgb *TypecastMessageGroupBy) sqlQuery() *sql.Selector {
	selector := tmgb.sql.Select()
	aggregation := make([]string, 0, len(tmgb.fns))
	for _, fn := range tmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tmgb.fields)+len(tmgb.fns))
		for _, f := range tmgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tmgb.fields...)...)
}

// TypecastMessageSelect is the builder for selecting fields of TypecastMessage entities.
type TypecastMessageSelect struct {
	*TypecastMessageQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tms *TypecastMessageSelect) Scan(ctx context.Context, v any) error {
	if err := tms.prepareQuery(ctx); err != nil {
		return err
	}
	tms.sql = tms.TypecastMessageQuery.sqlQuery(ctx)
	return tms.sqlScan(ctx, v)
}

func (tms *TypecastMessageSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := tms.sql.Query()
	if err := tms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
