// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jipark0716/discordTypecast/ent/predicate"
	"github.com/jipark0716/discordTypecast/ent/typecastmessage"
)

// TypecastMessageDelete is the builder for deleting a TypecastMessage entity.
type TypecastMessageDelete struct {
	config
	hooks    []Hook
	mutation *TypecastMessageMutation
}

// Where appends a list predicates to the TypecastMessageDelete builder.
func (tmd *TypecastMessageDelete) Where(ps ...predicate.TypecastMessage) *TypecastMessageDelete {
	tmd.mutation.Where(ps...)
	return tmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tmd *TypecastMessageDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tmd.hooks) == 0 {
		affected, err = tmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TypecastMessageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tmd.mutation = mutation
			affected, err = tmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tmd.hooks) - 1; i >= 0; i-- {
			if tmd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tmd *TypecastMessageDelete) ExecX(ctx context.Context) int {
	n, err := tmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tmd *TypecastMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: typecastmessage.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: typecastmessage.FieldID,
			},
		},
	}
	if ps := tmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// TypecastMessageDeleteOne is the builder for deleting a single TypecastMessage entity.
type TypecastMessageDeleteOne struct {
	tmd *TypecastMessageDelete
}

// Exec executes the deletion query.
func (tmdo *TypecastMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := tmdo.tmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{typecastmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tmdo *TypecastMessageDeleteOne) ExecX(ctx context.Context) {
	tmdo.tmd.ExecX(ctx)
}
