// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jipark0716/discordTypecast/ent/predicate"
	"github.com/jipark0716/discordTypecast/ent/usertypecastsetting"
)

// UserTypecastSettingDelete is the builder for deleting a UserTypecastSetting entity.
type UserTypecastSettingDelete struct {
	config
	hooks    []Hook
	mutation *UserTypecastSettingMutation
}

// Where appends a list predicates to the UserTypecastSettingDelete builder.
func (utsd *UserTypecastSettingDelete) Where(ps ...predicate.UserTypecastSetting) *UserTypecastSettingDelete {
	utsd.mutation.Where(ps...)
	return utsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (utsd *UserTypecastSettingDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(utsd.hooks) == 0 {
		affected, err = utsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserTypecastSettingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			utsd.mutation = mutation
			affected, err = utsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(utsd.hooks) - 1; i >= 0; i-- {
			if utsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = utsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, utsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (utsd *UserTypecastSettingDelete) ExecX(ctx context.Context) int {
	n, err := utsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (utsd *UserTypecastSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: usertypecastsetting.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usertypecastsetting.FieldID,
			},
		},
	}
	if ps := utsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, utsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// UserTypecastSettingDeleteOne is the builder for deleting a single UserTypecastSetting entity.
type UserTypecastSettingDeleteOne struct {
	utsd *UserTypecastSettingDelete
}

// Exec executes the deletion query.
func (utsdo *UserTypecastSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := utsdo.utsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usertypecastsetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (utsdo *UserTypecastSettingDeleteOne) ExecX(ctx context.Context) {
	utsdo.utsd.ExecX(ctx)
}
