// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// UserTypecastSetting is the predicate function for usertypecastsetting builders.
type UserTypecastSetting func(*sql.Selector)
